USE [VBM]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('SYS_LKP_CODE','U') IS NOT NULL
	DROP TABLE SYS_LKP_CODE
IF OBJECT_ID('SYS_LKP_CATEGORY','U') IS NOT NULL
	DROP TABLE SYS_LKP_CATEGORY

CREATE TABLE [dbo].[SYS_LKP_CATEGORY](
	[CATEGORY] [nvarchar](32) NOT NULL,
	[DESCRIPTION] [nvarchar](64) NOT NULL,
 CONSTRAINT [SYS_LKP_CATEGORY_PK] PRIMARY KEY CLUSTERED 
(
	[CATEGORY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[SYS_LKP_CODE](
	[CATEGORY] [nvarchar](32) NOT NULL,
	[CODE] [nvarchar](32) NOT NULL,
	[DESCRIPTION] [nvarchar](128) NULL,
	[RANKING] [int] NULL,
	[EXT_DESCRIPTION] [nvarchar](256) NULL,
	[CODE_GROUP] [nvarchar](32) NULL,
	[HISTORIC] [char](1) NULL,
 CONSTRAINT [SYS_LKP_CODE_PK] PRIMARY KEY CLUSTERED 
(
	[CATEGORY] ASC,
	[CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

ALTER TABLE [dbo].[SYS_LKP_CODE]  WITH NOCHECK ADD  CONSTRAINT [SYS_LKP_CODE_FK1] FOREIGN KEY([CATEGORY])
REFERENCES [dbo].[SYS_LKP_CATEGORY] ([CATEGORY])
ON UPDATE CASCADE
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[SYS_LKP_CODE] CHECK CONSTRAINT [SYS_LKP_CODE_FK1]
GO

