use VBM;
go

SELECT
	PF.ID_PORTFOLIO,
	PF.PERIOD,
	(PF.[SUM] - TFP.SUM2) as [SUM],
	PF.[SUM] as [SUM_PF],
	TFP.SUM2 as [SUM_TFP]
	

FROM GetPROFIT_FACT PF left join GetTAXES_FACTandPRED TFP
on PF.ID_PORTFOLIO = TFP.ID_PORTFOLIO and PF.PERIOD = TFP.PERIOD