use VBM;
go

SELECT
	CFP.ID_PORTFOLIO,
	CFP.PERIOD,
	(isnull(CFP.[SUM],0) - isnull(COFP.[SUM],0) - isnull(CPFF.[SUM],0) - isnull(TFP.[SUM2],0)) as [SUM],
	CFP.[SUM] as [SUM_CFP],
	COFP.[SUM] as [SUM_COPF],
	CPFF.[SUM] as [SUM_CPFF],
	TFP.[SUM2] as [SUM_TFP]
	

FROM GetCOLLECTIONS_FACTandPRED CFP left join GetCOSTS_OPER_FACTandPRED COFP
on CFP.ID_PORTFOLIO = COFP.ID_PORTFOLIO and CFP.PERIOD = COFP.PERIOD
left join GetCOSTS_PCT_FACT_FULL CPFF
on CFP.ID_PORTFOLIO = CPFF.ID_PORTFOLIO and CFP.PERIOD = CPFF.PERIOD
left join GetTAXES_FACTandPRED TFP
on CFP.ID_PORTFOLIO = TFP.ID_PORTFOLIO and CFP.PERIOD = TFP.PERIOD
order by 1,2