--плановые расходы
SELECT
	CP.ID_PORTFOLIO,
	CP.PERIOD,
		(CP.[SUM] - POP.[SUM] + AP.[SUM_CALC]) as [SUM],
	CP.[SUM] as [SUM_CP],
	POP.[SUM] as [SUM_POP],
	AP.[SUM_CALC] as [SUM_AP]
	
FROM GetCOLLECTIONS_PLAN CP left join GetPROFIT_OPER_PLAN POP
ON CP.ID_PORTFOLIO = POP.ID_PORTFOLIO and CP.PERIOD = POP.PERIOD
left join GetAMORTIZATION_PLAN AP
ON CP.ID_PORTFOLIO = AP.ID_PORTFOLIO and CP.PERIOD = AP.PERIOD