use VBM;
go

select 
	CFP.ID_PORTFOLIO,
	CFP.PERIOD,
	(
		CASE
			WHEN CFP.PERIOD = (select I.PURCHASE_DATE from PORTFOLIOS I where I.ID_PORTFOLIO = CFP.ID_PORTFOLIO)
				then (select P.PURCHASE_PRICE from PORTFOLIOS P where P.ID_PORTFOLIO = CFP.ID_PORTFOLIO) * (-1) - CIN.[SUM] + CFP.[SUM]
			ELSE
				(CFP.[SUM] - CIN.[SUM])
		END
	) as [SUM],
	
	CFP.[SUM] as [SUM_CFP],
	CIN.[SUM] as [SUM_CIN]

from GetCOLLECTIONS_FACTandPRED CFP left join GetCOSTS_IRR_NET CIN
on CFP.ID_PORTFOLIO = CIN.ID_PORTFOLIO and CFP.PERIOD = CIN.PERIOD
